[server]
headless = true
enableWatchdog = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2E86AB"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
